### PR TITLE
Reduce number of installed packages

### PR DESCRIPTION
**Pull request by Himura2la**
This set of packages works for built-from-source version, please test before merging

### CODE REVIEW

**Comment by Himura2la** [comment]
Moreover:
```
#6 1.184 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#6 1.186 Get:2 http://deb.debian.org/debian bullseye InRelease [113 kB]
#6 1.346 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [36.8 kB]
#6 1.505 Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [25.8 kB]
#6 1.655 Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8178 kB]
#6 5.781 Fetched 8397 kB in 5s (1765 kB/s)
#6 5.781 Reading package lists...
#6 6.515 Reading package lists...
#6 7.163 Building dependency tree...
#6 7.335 Reading state information...
#6 7.366 Package libappindicator3-1 is not available, but is referred to by another package.
#6 7.366 This may mean that the package is missing, has been obsoleted, or
#6 7.366 is only available from another source
#6 7.366
#6 7.505 E: Package 'libappindicator3-1' has no installation candidate
```

**Comment by rlespinasse** [comment]
Thanks @Himura2la I will test it

**Comment by Himura2la** [comment]
Replaced with https://github.com/rlespinasse/docker-drawio-desktop-headless/pull/15

**Comment by rlespinasse** [comment]
During this PR testing, I found a fix for #14 and that we can reduce even more the installed packages 🎉 
So your contribution has been integrated to #15, thank you @Himura2la

**Pull request closed without merging**
